Drop Table Questions
GO

Create Table Questions(
	id			int primary key auto_increment,
	Question	varchar(300),
	Answers		varchar(100),
	Correct		tinyint
);

GO

Insert Into Questions (Question,Answers,Correct) Values
--Cortez
('Qual a origem do nome Cortez?','É o nome do Baltazar:Uma família de amigos:Vem de um filme:É um nome automático!',2),
('Para melhorar uma arma de nível 1, qual minério é necessário?','Oridecon:Elunium:Phracon:Emveretarcon',3),
('Para melhorar uma arma de nível 2, qual minério é necessário?','Oridecon:Elunium:Phracon:Emveretarcon',4),
('Para melhorar uma arma de nível 3, qual minério é necessário?','Oridecon:Elunium:Phracon:Emveretarcon',1),
('Para melhorar uma armadura, qual minério é necessário?','Oridecon:Elunium:Phracon:Emveretarcon',2),
('Em quantos porcento a habilidade Perícia em Armamento nível 10 aumenta na chance de melhorar uma arma/armadura?','5%:10%:20%:30%',2),
('Quanto de defesa cada +1 em sua armadura lhe garante?','2:1:0.67:0.5',3),
('O que a habilidade Angelus lhe concede?','Defesa:Força:Agilidade:Defesa Mágica',1),
('Ao receber benção você fica com alguns atributos a mais. Quais são estes atributos?','Força e Agilidade:Destreza e Sorte:Força e Inteligência:Agilidade e Destreza',3),
('Do quê depende a força da habilidade `Curar`?','Nível de base e da cura e int:Nível de classe e int:Nível de classe e da cura:Int e nível de base',1),
('Quantas flechas a habilidade `Chuva de Flechas utiliza`','Nenhuma:Uma:Duas:Nove',1),
('O que a habilidade `Disparo Violento` faz?','Causa dano alto:Joga o alvo pra longe:Deixa alvo paralizado:Tira SP do alvo',2),
('Qual o elemento da habilidade `Espíritos Anciões`?','Água:Neutro:Fantasma:Sombrio',3),
('Quando você é petrificado, o que NÃO acontece?','+25% Defesa Mágica:+50% Defesa:Elemento fica terra:Perde 1% HP por segundo',2),
('Para quê a habilidade `Puxar Carrinho` é necessária em nível alto para mercadores e evoluções?','Andar mais rápido:Ter um carrinho:Carregar mais peso:Vender mais',1),
('Para quê a habilidade `Aumentar Capacidade de Carga` é necessária em nível alto para mercadores e evoluções?','Andar mais rápido:Ter um carrinho:Carregar mais peso:Vender mais',3),
('Para quê a habilidade `Comércio` é necessária em nível alto para mercadores e evoluções?','Andar mais rápido:Ter um carrinho:Carregar mais peso:Vender mais',4),
('Com a habilidade `Desconto` em nível máximo, quantos porcento a menos você paga ao adquirir um item no NPC?','30%:26%:24%:20%',3),
('Com a habilidade `Superfaturar` em nível máximo, quantos porcento a mais você recebe ao vender um item para o NPC?','30%:26%:24%:20%',3),
('Quanto de zeny você precisa para usar a habilidade `Mamonita` em nível 7?','0z:500z:700z:1000z',3),
('Quanto de zeny você precisa para usar a habilidade `Mamonita` em nível 10?','0z:500z:700z:1000z',4),
('Quanto de dano a mais você causa com a habilidade `Mamonita` em nível 7?','350%:450%:700%:1000%',2),
('Quanto de dano a mais você causa com a habilidade `Mamonita` em nível 10?','1200%:600%:900%:300%',2),
('Em qual nível é possível usar o carrinho mais avançado?','75:80:85:91',4),
('Em qual nível é possível usar o segundo carrinho?','40:50:55:60',1),
('Qual a área de efeito do `Cavalo-de-Pau`?','1x1:2x2:3x3:4x4:5x5:6x6',3),
('Qual status negativo a habilidade `Golpe Fulminante` pode causar?','Atordoamento:Petrificar:Sono:Veneno',1),
('Qual status negativo a habilidade `Petrificar` pode causar?','Atordoamento:Petrificação:Sono:Veneno',2),
('Qual status negativo a habilidade `Cantiga de Ninar` pode causar?','Atordoamento:Petrificar:Sono:Veneno',3),
('Qual status negativo a habilidade `Envenenar` pode causar?','Atordoamento:Petrificar:Sono:Veneno',4),
('O que a habilidade vigor aumenta?','Defesa:Defesa Mágica:Agilidade:Vitalidade',2),
('O que o atributo Força NÃO concede?','Capacidade de Peso:Dano ao usar armas:Dano ao usar arcos:Esquiva',4),
('O que o atributo Agilidade NÃO concede?','Esquiva:Velocidade de ataque:Velocidade de Movimento',3),
('O que o atributo Vitalidade NÃO concede?','Resistência à Cegueira:Resistência à Veneno:HP Máxima:Maior poder das poções',1),
('O que o atributo Inteligência NÃO concede?','Defesa Mágica:Ataque ao usar arcos:SP Máxima:Ataque ao usar magia',2),
('Quanto tempo é possível ficar escondido com Esconderijo nível 10?','30 segundos:1 minuto:2 minutos:5 minutos',4),
('O que a maldição NÃO causa?','Ataque -25%:Defesa - 25%:Sorte = 0:Velocidade de mov. diminuída',2),
('Como resistir melhor contra atordoamento?','Com SOR e VIT:Com VIT e INT:Com VIT e AGI:Com VIT e DES',1),
('Perto de paredes, qual a velocidade máxima quando em Furtividade?','80%:100%:130%:150%',3),
('Qual o máximo de dano possível de ser causado com a mão esquerda quando com duas adagas?','80%:100%:150%:200%',1),
('Qual o máximo de dano possível de ser causado com a mão direita quando com duas adagas?','80%:100%:150%:200%',2),
('Qual habilidade transforma o alvo em uma bomba de veneno?','Envenenar:Névoa Tóxica:Lâminas Destruidoras:Explosão Tóxica',4),
('Qual combinação abre o menu de atributos?','Alt+A:Alt+S:Alt+W:Alt+Q:Alt+E',1),
('Qual combinação abre o menu de habilidades?','Alt+A:Alt+S:Alt+W:Alt+Q:Alt+E',2),
('Qual combinação abre o menu de itens do carrinho?','Alt+A:Alt+S:Alt+W:Alt+Q:Alt+E',3),
('Qual combinação abre o menu de equipamentos?','Alt+A:Alt+S:Alt+W:Alt+Q:Alt+E',4),
('Qual combinação abre o inventário?','Alt+A:Alt+S:Alt+W:Alt+Q:Alt+E',5),
('Como fazer uma denúncia no CortezRO?','Entrando no Fórum:Mandando e-mail:Pelo MSN:Falando com GM',1),
('Um equipamento foi emprestado, mas a pessoa não quis devolver. O que acontece?','Ban e devolução do item:Ban sem devolução:Devolução pelos GMs:Nada',2),
('Quem mais pode ter a sua senha?','Amigos:Família:Só você mesmo:Os GMs',3),
('Qual o risco de usar `Força Violenta`?','Receber maldição:Receber atordoamento:Quebrar armadura:Quebrar arma',4),
('Os ferreiros têm uma habilidade para aumentar resistência à qual elemento?','Fogo:Morto-vivo:Água:Fantasma',1),
('Qual o ponto fraco de utilizar a Carta Sage Worm?','Zombie Master dá mais HP:Resistência à status negativo:Poções curam mais:É difícil de achar',2),
('Qual atributo negativo a Armadilha Luminosa causa ao oponente?','Sono:Atordoamento:Cegueira:Maldição',3),
('O que a Armadilha Extenuante causa ao oponente?','Dano alto:Perda de SP:Paralizamento:Sono',2),
('O que a Armadilha Congelante causa ao oponente?','Congelamento:Dano e congelamento:Dano:Paralizamento',1),
('Quando a habilidade `Instalar Mina` causa dano?','Quando usada:Após alguns segundos:Quando alguém a tocar:Nunca',2),
('Quando a habilidade `Armadilha Explosiva` causa dano?','Quando usada:Após alguns segundos:Quando alguém a tocar:Nunca',3),
('Por que a habilidade `Mensagem Secreta` é útil em batalha?','Dano:Deixa inimigo sem SP:Atributos que causa:É inútil!',4),
('O que a habilidade `Brandir Lança` NÃO exige?','20 de SP:Estar em um peco-peco:Estocada nível 3:Usar uma lança',1),
('O que significa [TR] no nome de um jogador?','Terrorista:Tutor:Tricolor:Tradutor',2),
('Como você pede suporte no CortezRO?','Gritando na cidade:Mandando broadcast:Usando o fórum:Email pro admin',3),
('O que não é preciso pra instalar o Cortez?','Instalar o bRO:Atualizar o bRO:Instalar o patcher:Desinstalar outros servidores',4),
('O que significa a palavra GM?','Game Master:Galinha Matadora:Gosta de Mexer:Garoto Maricas',1),
('Qual o máximo de slots que se encontra em uma vestimenta no CortezRO?','6:4:2:1',2),
('Qual o máximo de slots que se encontra em um armamento no CortezRO?','8:6:4:2',3),
('O ataque da habilidade Asura é maior em qual nível da habilidade?','5:4:3:1',4),
('Quantos slots uma asa tem no CortezRO?','4:3:2:1:0',5),
('Qual o local onde se equipa uma asa especial do CortezRO?','Cabeça-Baixo:Cabeça-Alto:Cabeça-Meio:Vestimenta',1),
('Quantos slots o item `Megingjard` tem?','4:3:2:1',2),
('Qual o nome do administrador do servidor?','Bola:Deus:Baltazar:SuperGM',3),
('Se você emprestar um item e ele não for devolvido, o que acontece?','Nada:GMs te dão outro item:Seu item é recuperado:O ladrão é banido',4),
('Para quem você pode passar sua senha?','Ninguém:Minha família:Meus amigos:Para os GMs',1),
('Quando você pode confiar em alguém que conheceu no jogo?','Depois de um tempo:Nunca:Quando ele me dá itens:Após encontro real',2),
('O que fazer quando alguém te dá um item muito bom de graça?','Aceitar e agradecer:Denunciar:Não aceitar:Pegar o item e sumir',3),
('Qual sistema de segurança o CortezRO NÃO tem?','Backups diários:Atualizações constantes:Firewall:Senha para jogadores',4),
('Qual carta permite esquivar da habilidade Asura?','Fumacento:Lord Of Death:Raydric:Sussurro:Deviling',1),

--Bruxo
('O que NÃO é requisito para Barreira de Fogo?','Lanças de Fogo Nv 4:Bolas de Fogo Nv 5:Chama Reveladora Nv 1:Ataque Espiritual Nv 4',4),
('O que acontece com o elemento de um monstro após ser congelado pela Rajada Congelante?','Muda para Água:Muda para Terra:Muda para Fogo:Muda para Vento',1),
('Quando você maximiza o Ataque Espiritual, quantas vezes o ataque mágico dará de dano?','1.6x:1.7x:2x:20x',2),
('Qual item é requisito para Petrificar?','Sangue Escarlate:Gema Azul:Gema Amarela:Gema Vermelha',4),
('Qual habilidade não é requisito para Escudo Mágico?','Ataque Espiritual Nv 4:Espíritos Anciões Nv 5:Aumentar Recuperação de SP Nv 6:Barreira de Gelo Nv 7',4),
('Quanto SP você irá regenerar, a cada 10 segundos, com nível 7 de Aumentar Recuperação de SP?','14:21:28:35',2),
('Você tem 50% SP, quanto de dano a Proteção Arcana irá reduzir e quanto SP será usado?','Dano 18%, SP 1.5%:Dano 18%, SP 2:Dano 24%, SP 1.5:Dano 24%, SP 2%',2),
('Qual o consumo de SP de Escudo Mágico no nível 10, e a quantidade de golpes absorvidos?','SP 40, 10 golpes:SP 35, 10 golpes:SP 40, 11 golpes:SP 35, 11 golpes',3),
('Qual o consumo de SP do Tempestade de Raios no nível 10?','84:74:64:54',2),
('Qual é a mallhor magia a ser usada na caverna de Byalan?','Relâmpago:Lanças de Fogo:Lança de Gelo:Chama Reveladora',1),
('Quem solta escudo com slot?','Besouro-Ladrão:PecoPeco:Pupa:Cobold de Maça',3),
('Qual monstro é o mais fácil para Magos?','Flora:Giearth:Golem:Névoa',1),
('Qual monstro é totalmente imune a Petrificar?','Salgueiro Ancião:Druida Malígno:Salgueiro:Cavalo-Marinho',2),
('Quanto de dano você causará com uma magia de vento num monstro água 3?','125%:150:175:200%',4),
('Filhote de Lobo do Deserto vs Familiar, quem ganha?','Filhote de Lobo do Deserto:Farmiliar:Empate:Não sei',1),
('Qual monstro não pode ser capturado como animal de estimação?','Poporing:Sapo de Rodda:Fumacento:Esporo Venenoso',2),
('Qual monstro é fraco contra o elemento fogo?.','Goblin de Punhal:Goblin de Maça:Cobold de Maça:Goblin de Martelo',4),
('Qual monstro tem a maior defesa mágica?','Horong:ChonChon:Andre:Caramelo',4),
('Qual monstro não pertence a este grupo.','Poring:Mastering:Ghostring:Esporo',4),
('Qual monstro não é morto-vivo?','Drake:Megalodon:Deviace:Khalitzburg',3),
('Qual o atributo mais importante para um Bruxo?','INT:AGI:DES:VIT',1),
('Qual elemento não tem magias do tipo lanças?','Água:Terra:Fogo:Vento',2),
('Não é caracteristica de um Bruxo?','Fracas habilidades físicas:Ataques a distância:Fazedor de dinheiro:Defesa mágica alta',3),
('Qual é a cidade natal dos Bruxos?','Prontera:Morroc:Alberta:Geffen',4),
('Qual carta tem nada a ver com o atributo Inteligência?','Carta Andre:Carta Andre Soldado:Carta Filhote de Lobo do Deserto:Carta Salgueiro Ancião',2),
('O que a classe dos Magos tem de superior sobre as outras classes?','Combate corpo a corpo:Esquiva Alta:Habilidades para dançar:Poderes mágicos',4),
('Qual é o bônus em inteligência no nível 40 de classe?','8:7:6:5',4),
('Qual item não pode ser equipado por Magos?','Faca:Boné:Sandália:Cajado',2),
('Durante o teste de Mago, Qual pedra NÃO é um catalisador?','Gema Amarela:Gema Vermelha:Gema Azul:Sangue Escarlate',4),
('Qual carta não tem nada a ver com mágica?','Carta Marduk:Carta Árvore Maldita:Carta Salgueiro:Carta Maya',2),

--Ferreiro
('Qual cidade e item local não combinam?','Morroc/Traje de Gatuno:Alberta/Machado:Comodo - Poção da Fúria Selvagem:Alberta - Maça',4),
('O que a técnica Martelo-Extremo faz?','Atordoa:Cega:Envenena:Faz Dormir',1),
('Em que o Mercador não é bom?','Abrir mercados:Comprar items:Vender caro:Correr rápido',4),
('Aonde você compra Gemas Azuis?','Alberta:Morroc:Geffen:Prontera',3),
('Que armas não podem ser usadas por Mercadores?','Stiletto:Demolidor:Mangual Pesado:Bíblia',4),
('Qual item tem a maior defesa?','Roupa de Baixo:Casaco de Pele:Armadura de Madeira:Manto de Seda',2),
('Quantas vezes você pode refinar uma arma de lvl 3 seguramente?','+3 :4 :5 :6 ',3),
('O que você pode fazer com Troncos?','Chapéu Chinês:Faixa Fantasma:Chifres Majestosos:Chifre de Alce',1),
('Qual cidade e item local não combinam?','Aldebaran/Folha de Ygg.:Alberta/Marreta:Comodo/Poção da Fúria Selvagem:Aldebaran/Marreta',4),
('Por quanto se vende um Jellopy?','1z:2z:3z:4z',3),
('O que é necessário para fazer um mercado?','Precisa ter carrinho:Item para vender:Ter uma arma equipada:Usar armadura',1),
('Aonde fica a Guilda dos Mercadores?','Alberta:Morroc:Geffen:Prontera',1),
('Em qual direção do relógio é a Loja de Armas de Morroc?','7 horas:11 horas:6 horas:5 horas',4),
('O que um Mercador não pode usar?','Main Gauche:Claymore:Mangual Pesado:Martelo de 2 Mãos',2),
('Qual item tem a maior defesa?','Roupa de Baixo:Casaco de Pele:Armadura de Madeira:Manto de Seda',2),
('Quantas vezes você pode refinar uma arma de lvl 4 seguramente?','+3:4:5:6',2),
('Qual monstro não dropa Minério de Ferro?','Chonchon:Chonchon de Aço:Zerom:Anolian',4),
('Que skill é necessário para se pegar Desconto?','Usar Carrinho Lv 3:Identificar Item:Mammonita Lv 10:Aumentar Capacida de Carga Lv 3',4),
('Que efeito o Martelo de Thor tem?','Atordoamento:Cegueira:Confusão:Veneno',1),
('Quanto de zeny é pego quando você usa Mammonita Lv 10?','900z:1,000z:2,000z:1,000,000z',2),
('Quanto dinheiro é economizado com o Desconto Lv 10??','21 % :22 % :23 % :24 % ',4),
('Quanto você pode ganhar com o Superfaturar Lv 10?','21 % :22 % :23 % :24 % ',4),
('Qual monstro dropa aço?','Zerom:Chonchon de Aço:Esqueleto Operário:Requiem',3),
('O que você pode fazer com Sangue Escarlate?','Coração Flamejante:Vento Bruto:Natureza Grandiosa:Gelo Místico',1),
('Qual minério você tem mais no banco?','WoV:Sangue Escarlate:Vida Verdejante:Cristal Azul',2),
('Que tipo de monstro é fraco contra a propriedade Vento?','Fogo:Água:Terra:Vento',2),
('Quantos ferros são necessários para fazer um aço?','5:4:3:6',1),
('O que você faz quando encontra uma pessoa estressada?','Faço uma denúncia:Converso por um tempo:Ignoro:Dropo um item e saio',2),
('Aonde você aprende a Personalizar Carrinho?','Aldebaran:Alberta:Morroc:Izlude',2),
('Cidade de Geffen é no centro, aonde fica a Guilda dos Ferreiros?','11oclock:5oclock:7oclock:12oclock',2),
('Qual cidade tem mais Ferreiros','Prontera:Morroc:Alberta:Geffen',4),
('Qual atributo afeta em forja?','FOR:DEX :AGI:VIT',2),

--Mercenário
('O que aqui NÃO É um pré-requisito da habilidade Tocaia?','Furtividade Lv 2:Ataque Sônico Lv 5:Esconder Lv 2:Perícia com Mão Esquerda Lv 2',4),
('Envenenar Arma faz sua arma que elemento?','Veneno:Terra:Fogo:Vento',1),
('Qual é a função do nível 4 de Perícia com Mão ESQUERDA?','Ataque +80% :Ataque +70%:Ataque +90%:Ataque +108%!!',2),
('Qual item você precisa usar quando você usa `Névoa Tóxica`?','Gema Verde:Gema Azul:Gema Amarela:Gema Vermelha',4),
('Quando você aumenta Envenenar Arma para o nível 5, qual nova habilidade irá aparecer?','Explosão Tóxica:Tocaia:Ataque Sônico:Névoa Tóxica',4),
('Que habilidade abaixo permite que você possa caminhar por ai despercebido?','Esconder:Recua:Furtividade:Chutar Areia',3),
('Qual é o requerimento para Névoa Tóxica?','Inimigo precisa ser fraco:Precisa usar uma Gema Vermelha:Você precisa ter uma quantia certa de HP',2),
('Qual carta dos monstros abaixo adiciona para Inteligência?','Chonchon de Aço:Deviruchi:Salgueiro Ancião:Baphomet',3),
('Quanto SP você gasta quando você bate dobrado usando uma adaga?','15:0:10:54',2),
('Qual é o melhor tipo de espada para se usar em Bybalan?','Espada do Vento da Perfuração:Espada de Gelo:Espada de Terra:Espada de Fogo',1),
('Qual monstro dropa Katar com slot?','Besouro-Ladrão Macho:PecoPeco:Lobo do Deserto:Cobold',3),
('Qual carta abaixo pode ser introduzida em uma Jur?','Caramelo:Ghostring:Baphomet Jr.:DoppelGanger',1),
('Qual classe pode forjar armas?','Mercador:Ferreiro:Gatuno:Sacerdote',2),
('Que arma abaixo não é uma arma da classe Katar?','Jur:Jamadhar:Infiltrador:Gladius',4),
('Em Bybalan uma grande quantidade de monstros são de que elemento?','Água:Fogo:Vento:Terra',1),
('Qual monstro abaixo não pode ser domado e se tornar um lindo bichinho de estimação?','Poring:Sapo de Roda:Lunático:Esporo Venenoso',2),
('Escolha o monstro que é fraco contra Fogo.','Cobold (Espada):Cobold (Maça):Cobold (Martelo):Cobold (Machado)',4),
('Escolha a NÃO-elemental Katar.','Katar da Chama Impetuosa:Katar da Espinheira Empoeirada:Osso Afiad de Carniçal:Infiltrador',4),
('Escolha o monstro que não pertence ao grupo.','Poring:Ghostring:Creamy:Drops',3),
('Escolha um NÃO-imortal monstro.','Drake:Esqueleto Arqueiro:Esporo Venenoso:Múmia Antiga',3),
('Qual é a taxa de esquiva aumentada quando você tem a habilidade `Aumentar Esquiva` no nível 1?','20:30:140:15',2),
('Qual monstro pode detectar alguém que está invisível/escondido?','Hodes:Sussurros:Porings:Munaks',2),
('Mercenários podem usar armas duplas.  Qual set das armas abaixo um Mercenário PODE usar?','Jur e Maça:Damascus e Claymore:Damascus e Stiletto:Machado e Stiletto',3),
('Em qual cidade você vira Gatuno?','Prontera:Lutie:Al De Baran:Morroc',4),
('Qual carta tem NADA para fazer com AGILIDADE?','Carta Baphomet Jr.:Carta Sussurro:Carta Besouro-Ladrão Macho:Carta Chonchon',2),
('O que faz os Mercenários tão especiais?','Habilidade de cantar:Habilidade de ação:Habilidade de dançar:Habilidade de esquiva',4),
('Quando um Mercenário alcança nível de classe 50, qual é o bonus adicionado que ele/ela recebe em Agilidade?','7:8:9:10',4),
('Qual equipamento não pode ser usado por um Mercenário?','Espada:Elmo Dourado:Adaga:Jur',2),
('Qual carta abaixo é inútil para um Mercenário?','Carta Ghostring:Carta Salgueiro Ancião:Carta Esqueleto Soldado:Carta Cobold',2),

--Cavaleiro
('Se encontrar um Aprendiz e ele lhe pedir um conselho, o que você diria para ele?','Um bom lugar para treinar:Daria algum dinheiro:Daria alguma arma:Ignoraria',1),
('Diga-me, qual dessas espadas não é uma que se pode usar com as Duas mãos?','Katzbalger:Espada Bastarda:Claymore:Flamberge',4),
('Muito bem, vou lhe perguntar sobre uma habilidade de Cavaleiro. Quais destas, NÃO é usada para atacar um oponente?','Perícia de Espada 2 Mãos:Instinto de Sobrevivência:Vigor:Golpe Fulminante',3),
('Cavaleiro é uma classe diferentes das outras, como um Cavaleiro poderá usar lanças e adquirir habilidades para estes fins. Qual dessas habilidades NÃO usa SP?','Perfurar:Lança Bumerangue:Estocada:Perícia em Montaria',4),
('O que você acha mais importante para um Cavaleiro?','Dinheiro:Fama:Honra:Mulheres',3),
('Lanças podem possuir propriedades elementais. Qual desses elementos é forte contra monstros do tipo Sombras/Mortos-Vivos?','Sagrado:Vento:Veneno:Terra',1),
('Um cavaleiro em um PecoPeco tem ataque e velocidade bem menores. Com a habilidade Pericia em Montaria em nível 3, qual a porcentagem da sua velocidade de ataque que se recupera?','70%:80%:90%:100%',2),
('Se você como Cavaleiro está em um grupo, e seu grupo é atacado, qual a sua ação?','Protege-los:Esperar os outros:Olhar, esperando os itens',1),

--Alquimista
('Quais desses itens não é necessário para a formação do Antígeno por um Alquimista?','Karvodailnirol:Detrimindexta:Álcool',1),
('Qual desses itens não é necessário no processo para fazer uma Mistura?','Karvodailnirol:Detrimindexta:Álcool',2),

--Arruaceiro
('Quanto é adicionado à taxa de esquiva que um Gatuno recebe quando aprimora a habilidade Perícia em Esquiva?','20:30:40:160',2),
('Escolha um monstro qu não pode detectar um personagem durante Esconderijo ou Furtividade?','Múmia:Rabo-de-Verme:Argos:Esqueleto Soldado',2),
('Onde se localiza a guilda dos Arruaceiros?','Comodo:Praia de Cocomo:Pharos, Ilha do Farol:Morroc',3),
('Em qual das seguintes cidades, é possível se tornar um Gatuno?','Comodo:Lutie:Alberta:Morroc',4),
('Escolha a carta que não afeta o atributo DES de um personagem...','Carta Rocker:Carta Múmia:Carta Zerom:Carta Drops',2),
('O que você acha legal em ser um Arruaceiro?','Ser um vagabundo:Ser um hipócrita:Ser um sem vergonha:Ter uma boa força de ataque',4),
('Em qual nível de classe um Gatuno pode se tornar um Arruaceiro?','Nível 20:Nível 30:Nível 35:Nível 50',4),
('Quais dessas cartas são inúteis para um Arruaceiro?','Carta Sussurro:Carta Salgueiro Ancião:Carta Zerom:Carta Matyr',2),
('Qual habilidade você deve aprender antes de aprender Túnel de Fuga?','Esconderijo:Furto:Perícia em Esquiva:Golpe Fulminante',1),
('Quanto de disconto um Arruaceiro pode conseguir com Extorquir a mais que a habilidade de Mercador, Disconto?','3%:2%:1%:0%',3),
('Qual é a descrição correta da habilidade Afanar?','Furta itens de jogadores:Furta itens de monstros:Furta Zeny de monstros:Furta Zeny de jogadores',4),
('Quantos Arruaceiros são necessários para ativar a habilidade Malandragem?','1 Arruacerio + 2 Mercenários:2 Arruaceiros + 1 Gatuno:4 Gatunos:2 ou + Arruaceiros',4),
('Depois de aumentar Remover Capacete para o nível 5, qual outra habilidade se tornará possível aprender?','Envenenar:Strip Tease:Explosão Venenosa:Remover Escudo',4),
('Escolha a habilidade que deixa você mover enquanto você permanece oculto?','Esconderijo:Recuar:Tunel de Fuga:Chutar Areia',3),
('Escolha a carta que aumenta a taxa de precião ao seu dono?','Andre:Familiar:Mumia:Marina',3),
('Escolha o monstro que recebe mais dano quando atacado com uma arma com Carta Vadon','Vadon:Deviruchi:Salgueiro Ancião:Bafomé',3),
('Quanto de SP o Ataque Duplo precisa quando usado com uma adaga?','15 SP:Não precisa de SP:10 SP:54 SP',2),
('Escolha a melhor adaga para ser usada no Tunel Submarino?','Main-Gauche Trovejante:Main-Gauche Glacial:Main-Gauche Terrestre:Main-Gauche Flamejante',1),

--Odalisca
('Qual é o efeito do Lamento de Loki?','Aumenta ataque de armas nv.4:Dobra o dano do grupo:Habilidades inutilizáveis:Aumenta vel.ataque',3),
('Qual é o nome do local onde você pode iniciar a mudança de sua ocupação para Odalisca?','Prontera:Morroc:Al De Baran:Comodo',4),
('Quantas cavernas são conectadas diretamente à vila de Comodo?','1:2:3:4',3),
('Qual do seguintes não pode ser domesticado?','Isis:Argiope:Dokebi:Deviruchi',2),
('Qual é uma das atrações principais de Comodo?','Igreja:Lojas:Frango Frito:Cassino',4),
('Qual é o efeito da Cantiga de Ninar?','Inimigos dormem/Área 5x5:Inimigos dormem/Área 9x9:Inimigos Deitam/Área 5x5:Inimigos Deitam/Área 9x9',2),
('Qual o efeito de Lições de Dança?','Aumenta INT:Aumenta dano de chicote:Aumenta dano de Bastão:Aumenta danos variados',2),
('Escolha o que uma Odalisca não pode fazer','Executar Danças:Atacar em longa distancia:Usar um chicote:Usar Espada de Duas Mãos',4),
('Qual é a cidade onde as Odalisca ficam que é a mais bonita?','Al De Baran:Juno:Morroc:Comodo',4),
('Quais são as vantagens da Odalisca?','Força Física:Habilidades:Capacidade de Dançar:Capacidade de Magia',3),
('Que é o nome do gerente do casino de Comodo?','Martine:Roberto:Moo:Deniroz',3),
('Quais itens a Odalisca não pode equipar?','Faixa de cabelo de gato:Espada de Duas Mãos:Sandálias:Brinco',2),
('Quantos faróis existem na Ilha de Comodo?','1:2:3',1),

--Templário
('Qual o atributo mais eficiênte para se atacar Mortos-Vivos?','Neutro:Terra:Morto-Vivo:Sagrado',4),
('Se um monstro for Morto-Vivo nível 2, quanto a mais o dano Sagrado causa comparado ao Fogo?','25%:50%:75%:100%',2),
('Qual desses itens você NÂO pode conseguir de um Druída Maligno?','Chapéu de Monge:Folha de Yggdrasil:Erva Branca:Amuleto',1),
('Qual desses montros Mortos-Vivos tem maior HP?','Ghoul:Skeleton Prisoner:Wraith Dead:Zombie Prisoner',3),
('Qual dos monstros a seguir tem o tamanho diferente dos demais?','Alma Penada:Khalitzburg:Drake:Druída Maligno',3),
('Qual dessas cartas te dá tolerância contra ataques da propriedade Morto-vivo?','Carta Orc Skeleton:Carta Orc Zombie:Carta Ghoul:Carta Skeleton Worker',2),
('Qual era o tipo de relacionamento entre Munak e Bongun antes dele morrerem?','Irmaõs:Amigos de infância:Meio-irmãos:Estranhos',2),
('Qual dos monstros a seguir não é agressivo?','Skeleton Soldier:Orc Skeleton:Skeleton:Skeleton Worker',3),
('Qual o nome do escudo em que a carta Munak foi inserida?','Escudo atômico:Escudo Amuleto:Escudo Hipnótico:Escudo Homeroth',2),
('Qual dos monstros a seguir não dropa Espólio?','Munak:Carniçal:Múmia:Soldado Esqueleto',1),
('Qual desses monstros tem o atributo diferente dos demais?','Karat:Wind Ghost:Isis:Wanderer',3),
('Qual espada é eficiente para atacar monstros Demoníacos?','Tsurugi Cruzada:Tsurugi Esburacada:Tsurugi Amaldiçoada:Tsurugi Sonolenta',1),
('Qual item NÃO é derrubado pelo Dokebi?','Minério de Elunium:Martelo de Ouro:Maça Espada:Cajado do Poder',2),
('Qual monstro Demoníaco tem mais HP?','Giearth:Magnólia:Dokebi:Marionete',4),
('Qual monstro Demoníaco tem o tamanho diferente dos outros?','Ghostring:Susurro:Deviruchi:Bafomé Junior',1),
('Qual escudo reduz os danos causados pelos monstros Demoníacos?','Escudo Satânico:Escudo do Inferno:Escudo Amuleto:Escudo Exelente',2),
('Qual atributo é mais efetivo no Alma da Ventania?','Água:Terra:Fogo:Vento',3),
('Qual monstro é diferente dos outros monstros Demoníacos?','Sohee:Ísis:Dokebi:Susurro',4),
('Qual efeito a Carta Marionete concede?','30% def contra sombrio:30% def contra veneno:30% def contra fantasma:30% def contra neutro',3),
('Qual das alternativas a seguir é um boa maneira de reagir quando encontrar um monstro Demoníaco?','Gritar `Ser malígno, vá embora!`:Oferecer sua alma:Usar Água Benta na arma:Usar chapéu de Deviruchi',3),
('Qual o nível da habilidade `Proteção Divina` necessário para aprender a habilidade `Flagelo do Mal?`','Nível 1:Nível 2:Nível 3:Nível 4',3),
('Se sua INT é 30, incluindo bonus de INT de seu equipamento, no nível 55, quanto de HP a habilidade `Curar` nível 5 restaura?','396:440:484:528',2),
('Com nível 7 de `Proteção Divina`, a sua defesa contra Mortos-vivos é aumentada em quanto?','21:22:23:24',1),
('Qual das lanças a seguir pode atacar o monstro `Pesadelo`, que é um monstro de atributo fantasma?','Lança:Guisarme-Bico:Foice:Zéfiro',4),
('Qual nível de `Curar` é necessário pra aprender a habilidade `Medicar`?','Nível 1:Nível 2:Nível 3:Nível 4',2),
('Qual é a velocidade de ataque quando a habilidade `Perícia em Montaria` Nível 3 é aprendida?','70% do normal:80% do normal:90% do normal:100% do normal',2),
('Qual das afirmações a seguir NÃO está correta sobra a habilidade `Flagelo do Mal`?','Mais ataque contra mortos:Apenas para Noviços:Mais ataque contra demônios:Habilidade Passiva',2),
('Quanto de SP a habilidade `Curar` nível 7 usa?','30:31:33:35',2),
('Qual atributo não pode ser curado com a habilidade medicar?','Maldição:Silêncio:Caos:Cegueira',1),
('O que melhor descreve um Templário?','Preparando para Matrimônio:Preparando para Guerra Santa:Preparando consumação:Preparando poções',2),

--Sábio
('O que o joalheiro de Morroc não vende?','Topázio:Granada:Diamante:Safira',2),
('Em que cidade você não compra ração para monstros?','Prontera:Morroc:Aldebaran:Alberta',3),
('Que cidade fica mais perto do labirinto da floresta?','Prontera:Morroc:Geffen:Payon',1),
('Qual desses monstros é de raça diferente dos outros três?','Muka:Drops:Plankton:Penomena',4),
('Todos estes monstros exceto um tem a mesma afinidade elemental. Qual tem a afinidade diferente?','Dokebi:Isis:Giearth:Deviruchi',3),
('Qual deles difere em tamanho aproximado dos outros?','Besouro-Ladrão Macho:Besouro-Chifre:Metaller:Argos',4),
('Qual destes monstros não solta folha de Yggdrasil??','Marduk:Bafomé Jr.:Angeling:Wanderer',1),
('Qual destas pessoas pode fazer a troca de classe para Sacerdote?','Padre Thomas:Bispo José:Windser Benedicto:Madre Maria',1),
('Quem não vive em Morroc?','Muda Armani:Aragham:Antonio:Abldul',3),
--('Qual das Kafra tem o cabelo azul bonito?','Pavianne:Debril:Claris:Tayelin',1),
('Qual não é necessário para destravar a habilidade Barreira de Fogo?','Lanças de Fogo Nv4:Ataque Espiritual Nv4:Bolas de Fogo Nv5:Chama Reveladora Nv1',2),
('Quando a habilidade `Aumentar Recuperação de SP Nv6` esta ativa, quanto de SP ahabilidade restaura a cada dez segundos??','14 sp:16 sp:18 sp:21 sp',3),
('Se você é um mago com classe nível 33, quantos pontos adicionais você receberá para inteligência?','7:6:5:4',4),
('Se a habilidade de arqueiro `Concentração Nv5` esta ativa,  quanto de SP ela irá consumir?','45 / 140sec:50 / 140sec:45 / 150sec:50 / 150sec',1),
('Qual delas não é necessário para destravar a habilidade de ferreiro `Amplificar Poder`?','Punho Firme:Resistência ao Fogo:Martelo de Thor:Manejo Perfeito',2),
--('Qual é o poder de defesa e a habilidade suplementar de uma Ribbon?','0 / SP +20:0 / SP +30:1 / SP +20:1 / SP +30',3),
('Qual classe não pode equipar um Manto Sagrado?','Monge:Mercador:Gatuno:Noviço',3),
('Qual alinhamento de estatus não pode ser removido com uma Poção Verde?','Silenciado:Envenenado:Atordoado:Amaldiçoado',4),
('Qual é o nome do reino antigo do qual Geffen descende?','Gefin:Geffenia:Gefdoria:Gefria',2),
('Qual árvore é dita ter a raiz do mundo?','Igg Drasil:Idrasil:Master:Antiga Árvore',1),
('Qual não é vendido na loja de itens mágicos de Geffen?','Capote:Vareta:Tiara:Manto Prateado',1),
('Qual cidade não vende lâminas?','Prontera:Izlude:Aldebaran:Payon',3),
('Que cidade fica mais perto de Glast Heim?','Prontera:Geffen:Morroc:Payon',2),
('Qual tipo de monstro é diferente dos outros três?','Estrela-do-Mar:Cavalo-Marinho:Marte:Marin',4),
('Qual afinidade ao elemental de um mostro difere dos outros?','Filhote de Lobo do Deserto:Fumacento:Picky:Choco',2),
('Qual dos monstros é de uma classe de tamanho diferente dos outros?','Drake:Alma Penada:Druida Malígno:Khalitzburg',1),
('Qual monstro não solta Fracon?','Pupa:Condor:Bebe Selvagem:Filhote de Lobo do Deserto',2),
('Quando você usa a habilidade `Escudo Mágico Nv6`,quanto de SP é consumido e quantos ataques ela irá bloquear?','SP 40, 6bl:SP 35, 6bl:SP 35, 7bl:SP 40, 7bl',4),
('Quando você usa `Ataque Espiritual Nv6`, qual é o poder de ataque relacionado com o MATK?','1.2x MATK:1.3x MATK:1.4x MATK:1.5x MATK',2),
('Qual deles cataliza a reação para fazer o liquido #4 durante o teste de classe para Mago?','Gema Azul:Gema Vermelha:Gema Laranja:Diamante de 1 quilate',4),
('Qual é o múltipo do dano e o consumo de SP para `Golpe Fulminante Nv6`?','250% / 8:280% / 8:280% / 15:310% / 15',3),
('Qual não é necessário para ativar a habilidade de caçador  Armadilha Explosiva`?','Remover Armadilha:Armadilha Atordoante:Instalar Armadilha:Armadilha Luminosa',1),
('Qual é o poder de defesa e a habilidade suplementar de um Veil?','0 / MDEF +3:0 / MDEF +5:1 / MDEF +3:1 / MDEF +5',2),
('Qual classe não equipa um Casaco?','Espadachim:Mago:Gatuno:Aprendiz',4),
('Qual item não é de cor azul?','Álcool:Detrimindexta:Karvodailnirol:Erva Azul',2),
('Qual metal pode mudar o destino do mundo?','Envertacon:Emperium:Enbera:Fracon',2),
('Qual deste sitens não é vendido na loja de presentes de Prontera?','Armadura Branca:Moldura Vermelha:Flor:Bolinha de Gude',3),
('Que cidade não vende Stilettos?','Prontera:Morroc:Geffen:Lutie',1),
('Que cidade é mais perto da Ilha das Tartarugas?','Aldebaran:Alberta:Comodo:Izlude',2),
('Qual dos monstros é de raça diferente dos outros três?','Raggler:Peste:Frilldora:Estrela-do-Mar',4),
('Qual monstro tem uma afinidade elemental diferente dos outros três?','Louva-a-Deus:Metaller:Rocker:Besouro-Chifre',2),
('Que monstro é de classe de tamanho diferente dos outros?','Raydric:Raydric Arqueiro:Wanderer:Dark Frame',1),
('Qual monstro não solta Álcool?','Besouro-Chifre:Plankton:Esporo Venenoso:Sapo-Cururu',3),
('Quanto de SP custa para usar `Tempestade de Raios Nv7`?','49:59:69:74',2),
('Se você tem 50% de seu SP sobrando, quanto de dano `Proteção Arcana` bloqueia e quanta SP será consumida?','24% bloqueado/1.5% SP:24% bloqueado/2% SP:18% bloqueado/1.5% SP:18% bloqueado/2% SP',4),
('Qual elemento não pode ser usado na forma de lanças pelo Mago?','Água:Terra:Fogo:Vento',2),
('Quando um Gatuno tem a habilidade `Ataque Duplo Nv7`, qual é a chance de ativação e o múltiplo da força de ataque?','35% / 120%:35% / 140%:40% / 120%:40% / 140%',2),
('Qual não é necessário para liberar a habilidade `Magnus Exorcismus`?','Proteção Divina:Curar:Ressuscitar:Aqua Benedicta',1),
('Qual é o poder de defesa e a habilidade suplementar de uma Orelha de Coelho?','1 / LUK +2:1 / LUK +5:2 / LUK +2:2 / LUK +5',3),
('Qual classe não equipa armaduras?','Espadachim:Mercador:Gatuno:Arqueiro',4),
('Que item restaura completamente HP e SP?','Geléia Real:Semente de YggDrasil:Fruto de YggDrasil:Mastela',3),
('Qual o nome do rei de Rune-Midgard?','Trisdan III:Tristan III:Traisda III:Trist III',2),
('A qual deus os Templários servem?','Odin:Loki:Tooru:Aragamsaree',1)