('O dano da habilidade "Bomba acida" é medido atravez da?','Força:Cartas da Arma:Inteligência:Destreza',3),
('Onde está localizada a Guilda dos Alquimistas?','Morroc:Yuno:Lighthausen:Aldebaran',4),
('Qual a raça do Emperium?','Amorfo:Anjo:Bruto:Inseto',2),
('Qual o melhor elemento, para bater no Emperium?','Sagrado:Sombrio:Fogo:Neutro',2),
('O Monstro Baphomet é fraco a que elemento?','Sagarado:Fogo:Gelo:Sombrio',1),
('O Bonus da Esquiva Perfeita, é medido pela Sorte, Qual multiplo deve ser seguido para que aumente esse bonus ?','Múltiplos de 2:Múltiplos de 7:Múltiplos de 3:Multiplos de 10',3),
('','OPT1:OPT2:OPT3:OPT4',NR_RESP),
('QUESTAO?','OPT1:OPT2:OPT3:OPT4',NR_RESP),
('QUESTAO?','OPT1:OPT2:OPT3:OPT4',NR_RESP),
('QUESTAO?','OPT1:OPT2:OPT3:OPT4',NR_RESP),
('QUESTAO?','OPT1:OPT2:OPT3:OPT4',NR_RESP),
('QUESTAO?','OPT1:OPT2:OPT3:OPT4',NR_RESP),
('QUESTAO?','OPT1:OPT2:OPT3:OPT4',NR_RESP),
('QUESTAO?','OPT1:OPT2:OPT3:OPT4',NR_RESP),
('QUESTAO?','OPT1:OPT2:OPT3:OPT4',NR_RESP),
('QUESTAO?','OPT1:OPT2:OPT3:OPT4',NR_RESP),
('QUESTAO?','OPT1:OPT2:OPT3:OPT4',NR_RESP),
('QUESTAO?','OPT1:OPT2:OPT3:OPT4',NR_RESP),
('QUESTAO?','OPT1:OPT2:OPT3:OPT4',NR_RESP),
('QUESTAO?','OPT1:OPT2:OPT3:OPT4',NR_RESP),
('QUESTAO?','OPT1:OPT2:OPT3:OPT4',NR_RESP),
('QUESTAO?','OPT1:OPT2:OPT3:OPT4',NR_RESP),
('QUESTAO?','OPT1:OPT2:OPT3:OPT4',NR_RESP),
('QUESTAO?','OPT1:OPT2:OPT3:OPT4',NR_RESP),
('QUESTAO?','OPT1:OPT2:OPT3:OPT4',NR_RESP),
('QUESTAO?','OPT1:OPT2:OPT3:OPT4',NR_RESP),
('QUESTAO?','OPT1:OPT2:OPT3:OPT4',NR_RESP),
